# command line: main.py --config config/nturgbd-cross-subject/default.yaml --work-dir work_dir/ntu/csub/ctrgcn --device 0 --num-worker 0 --save-epoch 0 --weights work_dir/ntu_new_graph/csub/ctrgcn/runs-12-30060.pt --start-epoch 12

base_lr: 0.1
batch_size: 16
config: config/nturgbd-cross-subject/default.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.ntu_rgb_d.MyGraph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 0
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 12
step:
- 35
- 55
test_batch_size: 16
test_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_CS.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_CS.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: work_dir/ntu_new_graph/csub/ctrgcn/runs-12-30060.pt
work_dir: work_dir/ntu/csub/ctrgcn
